const ADD_USER = "ADD_USER";
const UPDATE_USER = "UPDATE_USER";
const UPDATE_PROFILE = "UPDATE_PROFILE";
const ADD_ADDRESS = "ADD_ADDRESS";
const UPDATE_ADDRESS = "UPDATE_ADDRESS";

export {
	ADD_USER,
	UPDATE_USER,
	UPDATE_PROFILE,
	ADD_ADDRESS,
	UPDATE_ADDRESS
}